import Image from 'next/image';
import styles from './page.module.css';



export const metadata = {
    title: 'gomdilContact',
    description: 'Generated by Gomdil',
  }

const Contact = () => {
    return ( 
        <div className={styles.container}>
            <h1 className={styles.title}>Let;s Keep in Touch</h1>
            <div className={styles.content}>
                <div className={styles.imgContainer}>
                    <Image
                        src="/contact.png"
                        alt=""
                        fill={true}
                        className={styles.image}
                    />
                </div>
                <form className={styles.form}>
                    <input type="text" placeholder='이름' className={styles.input}/>
                    <input type="text" placeholder='이메일' className={styles.input}/>
                    <textarea className={styles.textArea} placeholder='메시지' cols="30" rows="10"></textarea>
                </form>
            </div>
        </div>
     );
}
 
export default Contact;