import Navbar from '../components/navbar/Navbar'
import Footer from '../components/footer/Footer'
import './globals.css'
import { Inter , Noto_Sans_Sora_Sompeng } from 'next/font/google'
import {ThemeProvider} from "../../context/ThemeContext"
import AuthProvider from '../components/AuthProvider/AuthProvider'


const inter = Noto_Sans_Sora_Sompeng({ subsets: ['latin'] })

export const metadata = {
  title: 'gomdilBlog',
  description: 'Generated by Gomdil',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">      
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
          <div className='container'>
            <Navbar/>
            {children}        
            <Footer/>
          </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
